# 文件路径: .github/workflows/build-and-push.yaml
name: Build and Push Docker Image

on:
  push:
    branches:
      - "master" # 或者 "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

          # [关键更新] 安装编译 eBPF 所需的完整依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          wget git golang clang llvm curl pkg-config build-essential zlib1g-dev \
          linux-headers-generic \
          libbpf-dev

      - name: Build Go application
        run: make build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME_ALI }}
          password: ${{ secrets.PASSWORD_ALI }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          # [关键更新] 修改镜像标签以匹配新项目
          tags: |
            registry.cn-hangzhou.aliyuncs.com/testwydimage/ebpf-injector:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
